import type { FoodGroupCategory } from "@prisma/client";

export const FOOD_GROUPS: { name: string; category: FoodGroupCategory; description: string }[] = [
  { name: "Leafy greens", category: "PRODUCE", description: "Spinach, kale, chard, lettuces." },
  { name: "Cruciferous veg", category: "PRODUCE", description: "Broccoli, cauliflower, cabbage, brussels sprouts." },
  { name: "Root veg", category: "PRODUCE", description: "Carrots, beets, turnips, parsnips." },
  { name: "Nightshades", category: "PRODUCE", description: "Tomatoes, peppers, eggplant, potatoes." },
  { name: "Alliums", category: "PRODUCE", description: "Onion, garlic, leeks, shallots." },
  { name: "Mushrooms", category: "PRODUCE", description: "Any variety, fresh or dried." },
  { name: "Legumes & pulses", category: "PROTEIN", description: "Beans, lentils, chickpeas." },
  { name: "Whole grains", category: "GRAIN", description: "Brown rice, farro, oats, whole wheat." },
  { name: "Refined grains", category: "GRAIN", description: "White rice, white flour, pasta." },
  { name: "Red meat", category: "PROTEIN", description: "Beef, lamb, goat." },
  { name: "Poultry", category: "PROTEIN", description: "Chicken, turkey, duck." },
  { name: "Pork", category: "PROTEIN", description: "Fresh pork and cured pork." },
  { name: "Oily fish", category: "PROTEIN", description: "Salmon, mackerel, sardines." },
  { name: "White fish", category: "PROTEIN", description: "Cod, halibut, tilapia." },
  { name: "Shellfish", category: "PROTEIN", description: "Shrimp, crab, mussels, clams." },
  { name: "Eggs", category: "PROTEIN", description: "Any preparation." },
  { name: "Dairy", category: "DAIRY", description: "Milk, cheese, yogurt, butter." },
  { name: "Fermented foods", category: "OTHER", description: "Kimchi, sauerkraut, miso, yogurt cultures." },
  { name: "Nuts & seeds", category: "PROTEIN", description: "Almonds, peanuts, sesame, sunflower seeds." },
  { name: "Fruit", category: "PRODUCE", description: "Fresh and dried fruit, any variety." },
  { name: "Starchy veg", category: "PRODUCE", description: "Corn, squash, plantain, sweet potato." },
  { name: "Chilli & heat", category: "FLAVOR", description: "Fresh and dried chillies, hot sauce." },
  { name: "Fresh herbs", category: "FLAVOR", description: "Cilantro, basil, parsley, mint, dill." },
  { name: "Warm spices", category: "FLAVOR", description: "Cumin, cinnamon, cardamom, clove." },
  { name: "Soy & tofu", category: "PROTEIN", description: "Tofu, tempeh, edamame, soy sauce." },
  { name: "Added sugar", category: "OTHER", description: "Refined sugar beyond what's naturally in an ingredient." },
  { name: "Fried & rich", category: "OTHER", description: "Deep-fried, heavy cream, butter-forward dishes." },
];

export const DIETS = [
  "Vegetarian",
  "Vegan",
  "Pescatarian",
  "Flexitarian",
  "Keto",
  "Low-carb",
  "Paleo",
  "Mediterranean",
  "Gluten-free",
  "Dairy-free",
  "Halal",
  "Kosher",
  "Low-sodium",
  "Diabetic-friendly",
  "High-protein",
];

export const ALLERGENS = [
  "Peanuts",
  "Tree nuts",
  "Milk",
  "Eggs",
  "Fish",
  "Shellfish",
  "Wheat/gluten",
  "Soy",
  "Sesame",
  "Mustard",
  "Celery",
  "Sulphites",
  "Lupin",
  "Corn",
  "Nightshades",
];
